### ISSUE TITLE
Add users to project

### ISSUE THREAD

**Issue by georgeoftown** [ubccr/coldfront#126]
Hi we are trying to see if we can use colfront in our Center

Trying to "Add users to project" we have this error. The user is marked as PI

`"POST /project/12/add-users-search-results/ HTTP/1.1" 200 3743
Internal Server Error: /project/12/add-users/
Traceback (most recent call last):
  File "/root/coldfront_app/venv/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/coldfront_app/venv/lib64/python3.6/site-packages/django/core/handlers/base.py", line 137, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view coldfront.core.project.views.ProjectAddUsersView didn't return an HttpResponse object. It returned None instead`

Thanks

**Comment by aebruno** [comment]
Thanks for reporting this bug! We're able to reproduce and will provide a fix shortly.

**Comment by mkzia** [comment]
Hello George,

Thanks for you interest in ColdFront. 

I am trying to duplicate the error you reported. 
Did you load the initial data? Did you load the sample test data? The updated installation instructions are here: https://ubccr.github.io/coldfront-docs/installation.html

Thanks

**Comment by mkzia** [comment]
No follow up, so closing issue.
