### ISSUE TITLE
Adding attributes cause attribute value error

### ISSUE THREAD

**Issue by jrlang** [ubccr/coldfront#142]
While try to add attributes to a resource we get the following errors.  They seem to have valid values for the attribute type.   Am I missing something?

Attribute type is "Paid"
  | Subscription attribute type | Value | Delete?
-- | -- | -- | --
Invalid Value "50000.00". Value must be a float.
  |  

Attribute tyoe is "PO"
Invalid Value "006778766". Value must be an integer.
--
  |

**Comment by mkzia** [comment]
Hello jrlang, 

Thank you for bringing this to our attention. There is a bug in the way we check for values. We will have this fixed tomorrow. 

Thanks,
--Mohammad
