### ISSUE TITLE
Projects: admin messages not displayed, no easy way to add them in UI

### ISSUE THREAD

**Issue by dsajdak** [ubccr/coldfront#194]
When updating an allocation, admins should be able to add a new message to the users.  There is no way to do this in the UI, only in the Django backend.  Even after adding an admin message on an allocation in the backend, it is not displaying in the allocation details in the UI.

**Comment by zooley** [comment]
When "... adding an admin message on an allocation in the backend ...", did you add this under "Allocation admin notes" or "Allocation user notes"? When testing, I noticed messages added under "Allocation user notes" are what seem to to show up on the front-end under "Messages from System Administrators" when looking at an allocation's details. Messages added under "Allocation admin notes", do _not_ appear on the front-end (from what I could see).

This may be a case of poor/confusing wording. Hopefully someone can correct me if I'm wrong, but I think "Allocation user notes" is meant as "Admin notes to the user" and "Allocation admin notes" is meant as "Admin notes to other admins".

In any case, I agree that a button on the front-end for adding a message directly from the allocations details page would make sense.

**Comment by dsajdak** [comment]
Verify that emails are sent to PIs when these messages are added.

**Comment by Iain-S** [comment]
I agree with @zooley that the wording is confusing and it isn't clear whether the user notes are meant to be left by or for the users. 

I think it would be great for both normal users / PIs and admins to be able to leave notes for each other via the Allocation Detail page.

**Comment by dsajdak** [comment]
Button to add notes on allocations and allocation change requests has been exposed via these PRs: https://github.com/ubccr/coldfront/pull/330
https://github.com/ubccr/coldfront/pull/346

Still to do is adding the button on the Project detail page and deciding if we want to allow users and managers to be able to add these.
