### ISSUE TITLE
Website is slow when accessing web pages for the first time while using "runsslserver"

### ISSUE THREAD

**Issue by labrjp** [ubccr/coldfront#196]
When using the HTTPS Protocol, all of the pages I go to are very slow.
Pages load very quick when I run the webserver without SSL.

This is one of the requests to the python web server.
"GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876

These 3 requests (Seem to be the most common requested files), seem to take awhile. 
"GET /static/c3js/c3.min.css HTTP/1.1" 200 2386
"GET /static/d3/d3.v5.min.js HTTP/1.1" 304 0
"GET /static/common/css/common.css HTTP/1.1" 304 0

I loaded up firefox developer mode, and looked at the console for the front page (not being logged in) --- I get these 2 errors: 

1) Loading failed for the <script> with source “https://coldfront-dev.hpc.inl.gov:8000/static/d3/d3.v5.min.js”.
2) Loading failed for the <script> with source “https://coldfront-dev.hpc.inl.gov:8000/static/c3js/c3.min.js”.

If I rename these 3 files. the website loads almost immediately.
I was wondering if some optimization to these files might be needed?

NOTE: --- after I click a few pages, and caching is done. all of the pages load very quick again.
I clear my cache / cookies / history, and attempt to visit the site again. 
Again VERY slow. this loading can vary. Usually around 2 minutes, but I've seen as long as 5 minutes.

I've re-installed coldfront several times testing this from beginning to end.
I've installed Coldfront onto a VPS, with Centos 7.7

Additional information you may asked for.
cat /etc/centos-release 
CentOS Linux release 7.7.1908 (Core)

Django version 2.2.4

SSL
----------------------------
1) I've put the public SSL Key here:
coldfront_app/venv/lib64/python3.6/site-packages/sslserver/certs/wildcard.key

2) I've installed the wildcard SSL Certificate here:
coldfront_app/venv/lib64/python3.6/site-packages/sslserver/certs/wildcard.intermediate.crt

3) I've modified coldfront_app/venv/lib64/python3.6/site-packages/sslserver/management/commands/runsslserver.py to match the names of the ssl certificate/public key

When I go to the website, I get a Green Lock in the address bar. (From my perspective everything related to the SSL Certificate is acting as it should)

I have 2 CPUs allocated to this VPS
load average: 0.45, 0.32, 0.34

4 Gigs of memory. Note that this VPS, only is being used for ColdFront, nothing else is running.

I am unable to find any error logs related to these requests to the web server to attempt more trouble shooting

**Comment by aebruno** [comment]
@labrjp are you using this for development or production? runsslserver is for development only. It is not meant to be run in a production environment. For production, we recommend running nginx or apache.

**Comment by labrjp** [comment]
@aebruno 
This is a development environment.
We are possibly looking into using this on a production server.
Testing all possible problems we may encounter.

Is there some kind of documentation on how to get this to load on a webserver, such as Apache or Nginx?

**Comment by labrjp** [comment]
lots of fiddling around, I was able to get Apache working with the site.
I've enabled SSL, and the site is loading quickly.
Thanks for pointing me in the right direction.

If anyone else is curious on how to do it.
you must load a module called wsgi

if using CentOS 7.7 like myself.
yum install wsgi 
does install this. however, that is compiled with python 2.7

I did manually compile wsgi following this:
https://modwsgi.readthedocs.io/en/develop/user-guides/quick-installation-guide.html

during the compile, you will need to install apxs
yum install httpd-devel

add this line to your httpd.conf file for apache
LoadModule wsgi_module modules/mod_wsgi.so


Example of what my VirtualHost looks like:
(Note, you will need to chance $HOSTNAME to equal your hostname)

<VirtualHost $HOSTNAME:80>
 ServerName $HOSTNAME
 DocumentRoot /opt/coldfront_app/coldfront
 WSGIScriptAlias / /opt/coldfront_app/coldfront/coldfront/config/wsgi.py

 # adjust the following line to match your Python path 
 WSGIDaemonProcess $HOSTNAME processes=2 threads=15 display-name=%{GROUP} python-home=/opt/coldfront_app/venv/
 WSGIProcessGroup $HOSTNAME


 <directory /opt/coldfront_app/coldfront>
   AllowOverride all
   Require all granted
   Options FollowSymlinks
 </directory>

 Alias /static/ /opt/coldfront_app/coldfront/coldfront/static/

 <Directory /opt/coldfront_app/coldfront/coldfront/static>
  Require all granted
 </Directory>
</VirtualHost>


Then of course if you want to install SSL for the site, you'll need to install mod_ssl
I followed this guide:
https://medium.com/@hbayraktar/how-to-install-ssl-certificate-on-apache-for-centos-7-38c25b84d8b1

**Comment by aebruno** [comment]
@labrjp Great! Thanks for providing the instructions. We're currently working on better documentation and will have some guides for deploying to production posted soon. Thanks for the great feedback. Any other questions let us know.
