### ISSUE TITLE
Document how to bulk import/export data

### ISSUE THREAD

**Issue by mkzia** [ubccr/coldfront#197]
FAQ: How do I bulk import resources?

Before bulk importing resources, let's first review the resource table. The tables in ColdFront are managed by the Django ORM. The ORM model definitions, which define the resource table and related tables, are defined [here](https://github.com/ubccr/coldfront/blob/master/coldfront/core/resource/models.py.  

A resource has the following required columns:
1. `resource_type` -- this column relates the `Resource` table to the `ResourceType` table. The `ResourceType`  table defines the types of resources that can be added to ColdFront. By default, ColdFront adds the following resource types: `Cloud`, `Cluster`,  `Cluster Partition`,  `Server`,  `Software License`, and `Storage`.  Other resource types can easily be added through the ColdFront admin site.
2. `name` -- name of the resource
3. `description` -- description of the resource

A resource can have the following optional columns:
1. `parent_resource` -- [default: Null] this column relates a resource to another resource that is its parent. This relationship can model a scenario, for example, where a cluster has many partitions where the parent resource itself is not allocatable, but its partitions are. 
2. `is_available` -- [default: True] a boolean to change the availability of a resource. Useful to disable users from requesting allocation to the resource.
3.`is_public` -- [default: True] a boolean indicating if everyone can request allocation to the resource or not. 
4. `is_allocatable` -- [default: True] -- whether the resource is allocatable or not. This column can be used in conjunction with the parent_resource column to allow users to request access to children resources and not to parent resources. 
5. `requires_payment` -- [default: False] -- used to indicate if the resource requires payment.
6. `allowed_groups` -- a many-to-many column that allows users to request access to the resource if they belong in a group that in the allowed_groups column. This column is useful when the `is_public` column is set to False. 
7. `allowed_users` -- a many-to-many column that allows users to request access to the resource if they are in this list of allowed users. This column is useful when the `is_public` column is set to False. 
8. `linked_resources` -- a -many-to-many column that automatically gives allocation to resources in the linked_resources column in addition to the resource itself. 

To bulk import resources, first create a spreadsheet with the resource information and export it as TAB delimited file. The following code block shows a list of resources with the columns that the importing script requires. NOTE: the tabs get lost when copying and pasting. Also some editors convert tabs to spaces. So be careful!

```
#name	description	resource_type	parent_resource	is_available	is_public	is_allocatable
Faculty Cluster	John's private cluster	Cluster		TRUE	FALSE	TRUE
General Cluster	Public Cluster	Cluster		TRUE	TRUE	TRUE
Test Cluster Main	Main Cluster	Cluster		TRUE	FALSE	FALSE
Test Cluster Partition1	Partition 1 of test cluster	Cluster Partition	Test Cluster Main	TRUE	TRUE	TRUE
Test Cluster Partition2	Partition 2 of test cluster	Cluster Partition	Test Cluster Main	TRUE	TRUE	TRUE
```

Drop the following piece of code in `coldfront/coldfront/core/utils/management/commands/import_resources_from_tsv.py`

```
import errno
import os

import argparse
parser = argparse.ArgumentParser()


from django.core.management.base import BaseCommand

from coldfront.core.resource.models import ResourceType
from coldfront.core.resource.models import Resource


class Command(BaseCommand):

    def add_arguments(self, parser):
        parser.add_argument(
            "-f", "--file", help="""Path to a tab seperated file with the following columns:
            name, description, resource_type, parent_resource, is_available, is_public, is_allocatable.""",
            type=str, required=True)

    def handle(self, *args, **options):

        filename = options['file']
        if not os.path.isfile(filename):
            raise FileNotFoundError(
                errno.ENOENT, os.strerror(errno.ENOENT), filename)

        with open(filename, 'r') as fh:
            for line in fh:

                if line.startswith('#'):
                    continue
                name, description, resource_type, parent_resource, is_available, is_public, is_allocatable = line.strip().split('\t')

                if is_available.strip().lower() == 'true':
                    is_available = True
                else:
                    is_available = False

                if is_public.strip().lower() == 'true':
                    is_public = True
                else:
                    is_public = False

                if is_allocatable.strip().lower() == 'true':
                    is_allocatable = True
                else:
                    is_allocatable = False

                resource_obj, created = Resource.objects.get_or_create(
                    name=name.strip(),
                    description=description.strip(),
                    resource_type=ResourceType.objects.get(
                        name=resource_type.strip()),
                    is_available=is_available,
                    is_public=is_public,
                    is_allocatable=is_allocatable
                )

                if parent_resource.strip():
                    parent_resource = Resource.objects.get(
                        name=parent_resource.strip())
                    resource_obj.parent_resource = parent_resource
                    resource_obj.save()

                print(resource_obj)
```
 

Import the resources: 

```
python3 manage.py import_resources_from_tsv --file <location_to_file>
```

**Comment by labrjp** [comment]
This worked perfectly for me. Thank you.

**Comment by aebruno** [comment]
Let's flesh out proper documentation for bulk importing and exporting data using the ColdFront python API. This document should show simple examples of how to do the following:

1. Importing users, resources, projects, and allocations - For example, a center has an existing system they use for storing this data and they would like to import this information into ColdFront. Show an example of parsing a simple CSV file of data and importing it into ColdFront
2. Exporting data. Show an example of a simple script to export project and allocation data to a CSV file. For example, a center needs to export data from ColdFront to another system.

Create a new markdown file under the "howto" section of our manual: `docs/pages/manual/howto`. Write the docs with good code examples. Show how to run the script using the django shell.

**Comment by hpc4you** [comment]
The 'RESOURCE ATTRIBUTES' section is missing ...
If I am going to import a slurm cluster via the cmd line, how to prepare the spreadsheet file? 

I would like to set 

1. `RESOURCE ATTRIBUTE TYPE` as `slurm_cluster`, 
2.  `VALUE` as `myhpc`.

**Comment by aebruno** [comment]
@hpc4you Great question. We're actively working on some documentation and sample code to demonstrate how to bulk import data. Hopefully we'll have to up soon.

In the interim, here's some sample python code to add resource attributes:

```python
from coldfront.core.resource.models import (Resource, 
                                           ResourceAttribute,
                                           ResourceAttributeType)

resource = Resource.objects.get(name="University HPC")
attr_type = ResourceAttributeType.objects.get(name="slurm_cluster")
resource_attr = ResourceAttribute.objects.update_or_create(resource_attribute_type=attr_type,
        resource=resource, defaults={"value": "myhpc"})
```

**Comment by hpc4you** [comment]
Thanks, @aebruno. 
Waiting for the updated documentation.
