### ISSUE TITLE
Slurm plugin:  DefaultAccount isn't always set

### ISSUE THREAD

**Issue by dsajdak** [ubccr/coldfront#232]
I am still trying to replicate the problem to determine which cases this doesn't get set.  Most of the time it does but not all the time.

**Comment by dsajdak** [comment]
This appears to be an issue with accounts that previously existed but were deleted and added back.

**Comment by dsajdak** [comment]
This issue https://github.com/ubccr/coldfront/issues/274 details this out so I'm closing this one

**Comment by dsajdak** [comment]
@aebruno I have tried everything I can think of to replicate this but I'm unable to.  It was a big problem ~18 months ago but now that I think of it, I have not noticed it recently and because I can't replicate it I'm wondering if a slurm update might have changed this behavior.  I can't see how that could be but until I see the problem come up again, I recommend we close this.

**Comment by aebruno** [comment]
Sounds good. If we see it again we can re-open.
