### ISSUE TITLE
Project status goes back to 'new' with review acceptance

### ISSUE THREAD

**Issue by mszpindler** [ubccr/coldfront#236]
Project review process seems to NOT update project status correctly. 

Actions:
Project status: new (force review) -> Review -> review pending -> Mark complete (by admin)

Result:
Project status: new
Review status: completed

I expect project status to change to 'active' after review is completed. Is is correct, should it be somehow configured?

**Comment by dsajdak** [comment]
I don't believe we do any automatic updating of project status.  We set our project status manually.  We use project reviews annually and the project is already in the active state.   Our process:
Our PIs create a new project - status=new.  
Admins change project status to active.  
A year goes by and our PI is forced to review the project.  If they don't they can't add new allocation requests or renew expiring allocations.  
Once the project review is submitted (project review=completed) they are allowed to do these things again.  None of this affects the project status though.  In fact, if we never change the project status from new to active, it doesn't affect anything.

We have not considered your use case before.  It sounds like you want to have a PI review a brand new project.  Is that correct?

**Comment by mszpindler** [comment]
Thank you. I misunderstood review concept.

Is there any practical difference between project in "new" and "active" state?

**Comment by dsajdak** [comment]
@mszpindler I'm so very sorry that I didn't realize you replied with more questions.  We automate user access based on allocation status.  If a PI creates a new project and doesn't request an allocation for it, they will have access to nothing.  This is often confusing for them and a stumbling block.  Being able to see the 'new' projects easily helps us avoid that issue.  We don't currently have email notifications setup for new projects but that's something I'd like to add or list off the Admin menu showing the new projects easily.
