### ISSUE TITLE
Publications:  Anything with special characters in the title fail to be added to project

### ISSUE THREAD

**Issue by dsajdak** [ubccr/coldfront#247]
Publications with special characters in the title fail to be added to the project.  Examples of these characters include scientific formulas.

User gets error:  We're having a bit of system trouble at the moment. Please check back soon!

From logs:  django.db.utils.OperationalError: (1267, "Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='")

**Comment by dsajdak** [comment]
First step would be to improve this messaging.  If a publication can't be added, the error should say that, rather than just "system trouble."  Something like "This publication could not be added.  If there are special characters or scientific formulas in the title, please add the publication manually."

**Comment by aebruno** [comment]
This is because currently we're not setting the default charset and in mariadb/mysql 5.5 it's defaulting to latin1. We really need to change this to utf8mb4 for mysql/mariadb. The short term fix is to run this directly on the db: ```ALTER TABLE publication_publication CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;```
