### ISSUE TITLE
Configuration: python errors in local_settings.py cause misleading error message

### ISSUE THREAD

**Issue by chanwilson** [ubccr/coldfront#254]
Ran across this while trying to turn on LDAP support.  As both `python-ldap` and `django_auth_ldap` are required for use, just blindly uncommenting those lines from the sample config results in the misleading error message
```
local_settings.py file is required. Copy coldfront/config/local_settings.py.sample to local_settings.py
```

Additionally, the doc and sample config should be updated to mention the required python modules for use.

**Comment by aebruno** [comment]
@chanwilson Thanks for reporting this. We re-factored how we handle settings/config. See #264. We also added some better documentation available here: https://coldfront.readthedocs.io

Going to close this out but feel free to re-open if you have any other issues. Thanks!
