### ISSUE TITLE
Fix URL under project_urls, Documentation

### ISSUE THREAD

**Issue by ShiweiJuliaHuang** [ubccr/coldfront#257]
Documentation url under "project_urls" displays a 404 error.  
 project_urls={
        'Bug Tracker': 'https://github.com/ubccr/coldfront/issues',
        'Documentation': 'https://ubccr.github.io/coldfront-docs/',
        'Source Code': 'https://github.com/ubccr/coldfront',
    },

**Comment by aebruno** [comment]
Thanks for spotting this! Fixed in bcd3113757c9db9da39b2ce3dc2104ebf69d069d
