### ISSUE TITLE
introductory text seems lacking

### ISSUE THREAD

**Issue by fdouglis** [ubccr/coldfront#281]
OK, I'm a new user.  Trying the readthedocs guide but it's leaving me scratching my head.

Once I got past the previous issue of a missing file, it installed fine.    I then run with a really simple env file based on the guide -- the only real difference is specifying sqlite3 for the DB.

> DEBUG=True
> CENTER_NAME='Perspecta Labs'
> PROJECT_ENABLE_PROJECT_REVIEW=False
> DB_URL=django.db.backends.sqlite3://///home/fdouglis/tools/coldfront/coldfront.db

The initial setup is practically a no-op, which is surprising:

> COLDFRONT_ENV=coldfront.env coldfront initial_setup
> Operations to perform:
>   Apply all migrations: admin, allocation, auth, contenttypes, django_q, field_of_science, grant, project, publication, research_output, resource, sessions, user
> Running migrations:
>   No migrations to apply.
> Adding field of science ...
> Finished adding field of science

Then if I try another operation, I get something saying I failed to migrate:

> coldfront createsuperuser
> 
> You have 40 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, allocation, auth, contenttypes, django_q, field_of_science, grant, project, publication, research_output, resource, sessions, user.
> Run 'python manage.py migrate' to apply them.
> 
> Traceback (most recent call last):

And this is followed by a huge number of lines of trace indicating a failure, which I can include if needed.  But I'm guessing the `unapplied migrations` versus the `No migrations to apply` suggests some sort of initialization disconnect?

Is there anything along the lines of a total beginner's tutorial that I am missing here?  Even this issue aside ... I looked at the examples of how to configure, and it shows gifs of entering info into some sort of interface I assume is a web page -- but I'm not finding how I actually reach that web page.  ~~I'm sure it's there someplace....~~ I see the reference to localhost:8000 later in the initial setup guide -- repeating it on the page that talks about the interface couldn't hurt ....

**Comment by fdouglis** [comment]
A follow-on.  I note that [readthedocs](https://coldfront.readthedocs.io/en/latest/install/) says it's ready to use after `coldfront initial_setup` but I couldn't figure out initially how to follow the directions to run migrate.py (as I couldn't find such a beast).  I tried `coldfront migrate` and this time it said it was doing a bunch of things.

**Comment by aebruno** [comment]
> Once I got past the previous issue of a missing file, it installed fine. I then run with a really simple env file based on the guide -- the only real difference is specifying sqlite3 for the DB.

> DB_URL=django.db.backends.sqlite3://///home/fdouglis/tools/coldfront/coldfront.db

The value you have for `DB_URL` is wrong. See the documentation [here](https://coldfront.readthedocs.io/en/latest/config/#database-settings). You're setting should look something like this:

```
DB_URL=sqlite:////home/fdouglis/tools/coldfront/coldfront.db
```

**Comment by fdouglis** [comment]
Ah - I had that originally but when I ran into those other issues I tried changing it to the `3` variant.  

So if it didn't like that, shouldn't it have complained it was a bad backend, instead of saying it didn't actually do anything? :) 

Indeed, my later runs of coldfront were copied from the intro page and I didn't include the env override.  That's probably why the migration worked that time.  

Thanks and sorry for a smack of red herring.  

Overall though the documentation is kinda confusing because of the various cross-links (e.g. for configuration).  Is there  a "hello world" style "here's how to get from installation to simple project" in one place?  Again, maybe I'm just not following the right links.

**Comment by dsajdak** [comment]
@fdouglis Under the 'Manual' section of readthedocs you'll find info about all the pieces of ColdFront.  For a nice tutorial, I recommend you check out the section on ColdFront here:  https://github.com/ubccr/hpc-toolset-tutorial - this will not line up with your fresh install of ColdFront but the docker container setup for this tutorial is really slick and has all you need to test out ColdFront, if you want.  We're also happy to provide a demo over Zoom.  Feel free to email us if you'd like to setup something up:  CCR-COLDFRONT-ADMIN-LIST@LISTSERV.BUFFALO.EDU

**Comment by fdouglis** [comment]
That link looks promising, thanks!  

BTW, regarding my having the wrong setup - I think maybe your documentation is wrong, or you simply behave differently depending on one's setup.  I changed it back to just `sqlite` and got:

`Traceback (most recent call last):
  File "/home/fdouglis/tools/venv/lib/python3.8/site-packages/django/db/utils.py", line 110, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django.db.backends.sqlite'

But with sqlite3 it worked fine.  

`

**Comment by aebruno** [comment]
> So if it didn't like that, shouldn't it have complained it was a bad backend, instead of saying it didn't actually do anything? :)

Yes, good point. We can add some more checking there. 

> Is there a "hello world" style "here's how to get from installation to simple project" in one place? Again, maybe I'm just not following the right links.

For a "hello world" style quick start, I recommend just following the [install guide](https://coldfront.readthedocs.io/en/latest/install/) exactly and not adding in any custom configs. By default, it will create a sqlite db in your current working directory. Looks like you were confused when trying to add some custom configs which is arguably more advanced than "hello world".

**Comment by fdouglis** [comment]
The only reason I added the custom config was that it looked like by default it would use mysql involving connectivity over some port -- this system is kind of locked down and I wanted to avoid that, so when I saw an alternative used a file instead, I opted for that.

**Comment by aebruno** [comment]
> The only reason I added the custom config was that it looked like by default it would use mysql involving connectivity over some port -- this system is kind of locked down and I wanted to avoid that, so when I saw an alternative used a file instead, I opted for that.

Curious why you thought it used mysql by default? Perhaps we can make that more clear. We do have a note in [our docs](https://coldfront.readthedocs.io/en/latest/install/#intializing-the-coldfront-database) about this.

**Comment by aebruno** [comment]
> BTW, regarding my having the wrong setup - I think maybe your documentation is wrong, or you simply behave differently depending on one's setup. I changed it back to just `sqlite` and got:
>
> ModuleNotFoundError: No module named 'django.db.backends.sqlite'
> 
> But with sqlite3 it worked fine.

Thanks for pointing this out. We haven't seen this in our testing but will make a note in the docs. Thanks for all the great feedback!

**Comment by fdouglis** [comment]
> Curious why you thought it used mysql by default? Perhaps we can make that more clear. We do have a note in our docs about this.

Hmm, now so am I! I just looked back and saw:

>  By default, ColdFront will use SQLite and create a database file in your current working directory.

That is all good!  My guess is that I saw this in the _sample_ configuration and thought I should emulate it but change it to sqlite(3):


> DB_URL='mysql://user:password@127.0.0.1:3306/database'
