### ISSUE TITLE
Install documentation has incorrect usernames for test_data

### ISSUE THREAD

**Issue by mrobbert** [ubccr/coldfront#309]
The install documentation lists ccollins and michardson as valid users that can be used once test data has been loaded, but they don't work. 
Looking at the code it looks like, other than admin, only sfoster and cgray are valid users that are created.

**Comment by dsajdak** [comment]
@mrobbert Thanks for catching that!  We will update the documentation.

**Comment by Iain-S** [comment]
See PR #310
