### ISSUE TITLE
Port Allocation Change Request features to Allocation Requests

### ISSUE THREAD

**Issue by dsajdak** [ubccr/coldfront#341]
With the allocation change request feature we modified some of the process flow.  This process should be ported back to the allocation requests for a more seamless process across the two.  What to update on allocation requests:

Allocation detail page:
- Expose button to add 'notifications' so admin can include details about allocation request
- Allow 'lock/unlock' to be set here like the 'allow change requests'

Allocation request list:
- Change 'Date Requested/Last Modified' to 'Last Modified'
- Change 'Allocation Actions' to 'Actions'
- Add 'Details' button to get to Allocation detail page
- Unlink ID number as this will now be the 'Details' button
- Grey out 'Activate' if allocation is new - this is because allocation attributes need to be added to new allocations before allocation is approved
- Remove 'Deny' button and require admin to use 'Details' to specify a reason for denying an allocation

**Comment by dsajdak** [comment]
After discussion, we decided:
- Activate button on 'Allocation Requests' list will be greyed out for new allocations, forcing admin to view the allocation details
- We will not require allocation attributes but admin will get a pop-up asking if they're sure they want to activate an allocation with no attributes
- Also will not require a reason for a denial but admin will get a pop-up asking if they want to provide a reason

**Comment by aebruno** [comment]
Closed in #346
