### ISSUE TITLE
Mention collect static for "SITE_STATIC" usage

### ISSUE THREAD

**Issue by lebonez** [ubccr/coldfront#358]
Just an info for newer users like myself, when running the application through nginx using /static alias in nginx conf, collectstatic will need ran everytime you add/modify custom SITE_STATIC files. The dev runserver will handle this fine without collectstatic but nginx will just result in looking in your nginx conf alias directory and not in SITE_STATIC using django finders

I was going to do a pull request but wasn't entirely sure where this note should be added in the docs. My guess is a note around here? 
https://github.com/ubccr/coldfront/blob/master/docs/pages/config.md?plain=1#L298

**Comment by aebruno** [comment]
> I was going to do a pull request but wasn't entirely sure where this note should be added in the docs. My guess is a note around here? https://github.com/ubccr/coldfront/blob/master/docs/pages/config.md?plain=1#L298

Yes, adding it there works great I think as it's related to custom branding.
