### ISSUE TITLE
Publications:  Duplicate publication on project needs better error

### ISSUE THREAD

**Issue by dsajdak** [ubccr/coldfront#369]
If a user tries to add a publication to their project that is already there, they get the error "sorry something went wrong, try again later"

ColdFront is showing the reason correctly so this needs to be displayed to the user:

django.db.utils.IntegrityError: (1062, "Duplicate entry 'DOI' for key publication_publication_project_id_unique_id_xxxxxx_uniq'")

**Comment by aebruno** [comment]
Fixed in #367
