### ISSUE TITLE
"Select all" allocations behaves not as expected in 'Add user to project'

### ISSUE THREAD

**Issue by mdzik** [ubccr/coldfront#396]
![Screencast_01 04 2022_13_22_51](https://user-images.githubusercontent.com/3542727/168073497-c6e03f36-a277-4615-af8b-99fa554b7437.gif)

We found that lines responsible are around here:

https://github.com/ubccr/coldfront/blob/75d90d657ca52cb1df90a0fd0adbb33ec97b51a7/coldfront/core/project/templates/project/add_user_search_results.html#L90

as input's are numbered from 0 not 1.  I could PR fix but this might have been triggered by some local modifications - could you confirm it?

**Comment by dsajdak** [comment]
Hi @mdzik I can confirm we're seeing the same issue.  If you don't mind submitting a fix for it we'd gladly accept.  If you don't have time, we do have a student that can push this out next week.  Thanks!
