### ISSUE TITLE
Expire sessions X seconds after the last activity

### ISSUE THREAD

**Issue by aebruno** [ubccr/coldfront#452]
Currently, sessions expire after 15 minutes. This is hard coded in settings [here](https://github.com/ubccr/coldfront/blob/master/coldfront/config/auth.py#L18). What we really want is to keep the session alive as long as the user is doing something. Once they become inactive after X seconds, the session should expire. 

Let's make the following modifications:

1. Use this module [django-session-timeout](https://pypi.org/project/django-session-timeout/) in auth.py 
2. Add support for setting `SESSION_EXPIRE_SECONDS` and `SESSION_EXPIRE_AFTER_LAST_ACTIVITY` via env variables.
3. We probably need to unset `SESSION_COOKIE_AGE` or set session to expire at browser close. [See here](https://docs.djangoproject.com/en/4.1/topics/http/sessions/#browser-length-vs-persistent-sessions)

**Comment by dsajdak** [comment]
@aebruno I thought this time out was related to mokey/openid because we have the same issue with OnDemand.
