### ISSUE TITLE
Version in the UI does not change after upgraded from 1.1.3 to 1.1.4

### ISSUE THREAD

**Issue by carvinch** [ubccr/coldfront#508]
I upgrade coldfront from 1.1.3 to 1.1.4.
In the backend, the coldfront version and  database are all upgraded.
I can see 7 new tables are added into the database.
But from the UI, it still shows the version of 1.1.3.

**Comment by carvinch** [comment]
Solved , all works fine currently.

**Comment by dsajdak** [comment]
@carvinch I'm curious if you did anything else to make this work?  We have others reporting similar issues with upgrading

**Comment by carvinch** [comment]
We create a new env by python39 in the same directory, and then upgrade in the new env, after that it works.
