### ISSUE TITLE
can't log in to site using test data set

### ISSUE THREAD

**Issue by GentleInfant** [ubccr/coldfront#527]
I followed the instructions on https://coldfront.readthedocs.io/en/latest/install for a test environment, however I can't log in with either the superuser I created or any of the users in the demo dataset. Each time I try it kicks me back out to the login screen with the box titled 'Do not have an Account?'.

Noticeably this is different to if I just enter nonsense for the username/password in which case I get a red box that says 'Please enter a correct username and password. Note that both fields may be case-sensitive'.

It's behind nginx reverse proxy because this is on a headless box a few people would like to poke at for a bit before any decisions are made. The nginx entry is currently (I've tried a few different things):

```
    server {
        listen       80;
	listen       [::]:80;

	location / {
	    proxy_set_header Host $host;
	    proxy_set_header X-Real-IP $remote_addr;
	    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	    proxy_set_header X-Forwarded-Proto $scheme;
	    proxy_pass http://127.0.0.1:8000;
	}
    }

```

What obvious thing am I missing?

**Comment by aebruno** [comment]
Do you have `DEBUG=True`? https is required. So you'll need to set `DEBUG=True` if you don't have ssl enabled.

**Comment by GentleInfant** [comment]
Yep!

As I said I followed the instructions on the page. They said to set `DEBUG=True` so I did! I also tried some other combinations of options (some which didn't include it) without any luck.

**Comment by dsajdak** [comment]
@GentleInfant did you resolve this issue?  It has to be something with the nginx proxy.  If you're not able to get it to work, we do have configs for a more production worthy setup here: https://coldfront.readthedocs.io/en/latest/deploy/

**Comment by GentleInfant** [comment]
No I haven't yet. Got sidetracked with other tasks. Probably is something about the nginx proxy but I don't feel like I usually have this trouble so clearly something small and annoying!

**Comment by GentleInfant** [comment]
Closing the ticket. I didn't end up solving it but it's not wanted anymore by the person who requested it.
