### ISSUE TITLE
Feature: further documentation on xdmod_plugin usage, core_hours and service units

### ISSUE THREAD

**Issue by ds-04** [ubccr/coldfront#626]
### Description

It would be very useful to have some further information on the xdmod_plugin, core hours (displayed in coldfront on the allocation) and service units.

At the moment im testing Coldfront using two systems (VM1 coldfront+slurm master/client and VM2 xdmod).

- I've run some jobs through a test slurm instance and with the account created by an allocation (and updated within slurm)
- This has been shredded and ingested in xdmod - I can see the graphs
- I'm executing the xdmod_plugin (for total_cpu_hours) but am not seeing anything happening in CF dashboard.
- At the moment the updating of the core_hours shown on an allocation isn't clear to me.
- I cant see anything in the documentation about service units within CF. Is this something sites have developed completely themselves? 

### Component

Other

**Comment by ds-04** [comment]
For ```coldfront xdmod_usage``` to work... e.g. ```coldfront xdmod_usage -sx -m total_cpu_hours```

It appears that in CF django admin a **_Resource Attribute Type_** needs added:

| Name | Attribute type name |
| --- | --- |
| xdmod_resource | Text |

Then the Resource (in this case a slurm cluster) needs this Resource attribute type added

| Resource attribute type  | Value |
| --- | --- |
| xdmod_resource | slurm_cluster_as_named_in_slurm |


Now the syncer appears to be connecting (in my case had to deal with self signed test cert on the test xdmod instance I'm running - python requests) ... graphs not updated in CF yet, because it can't find the data xdmod end, but working on that

**Comment by ds-04** [comment]
Further notes: 

- Xdmod self signed cert in testing environ needs to be appended into the Coldfront Certifi cert bundle, in Coldfront venv, so the ``coldfront xdmod_usage`` syncer can trust the XMOD url
- Need to ensure XDMOD is using the Slurm account - you must use "pi_column": "account_name" in the the ``resources.json`` - https://open.xdmod.org/11.0/configuration.html

**Comment by aebruno** [comment]
Fixed in #633
